<?php
/** @var States $oEntity */
/** @var string $sHeading */
use Bitfalls\Utilities\Stringer;

?>

<h3><?php echo $sHeading; ?></h3>

<form class="form-horizontal" action="/admin/geo/upsertstate" method="post">
    <fieldset>
        <input type="hidden" value="<?= $oEntity->getId(); ?>" name="id"/>

        <?php

        $aFields = array(
            'name' => 'Name',
            'short_name' => 'Short Name'
        );

        foreach ($aFields as $k => &$v) : $sMethod = 'get' . Stringer::toCamelCase($k); ?>
            <div class="control-group">
                <label class="control-label" for="<?= $k ?>"><?= $v ?></label>

                <div class="controls">
                    <input
                        type="text"
                        required="required"
                        name="<?= $k ?>"
                        id="<?= $k ?>"
                        placeholder="<?= $v ?>"
                        value="<?= $oEntity->$sMethod(); ?>"
                        >
                </div>
            </div>
        <?php endforeach; ?>
        <div class="control-group">
            <label class="control-label" for="country">Country</label>

            <div class="controls">
                <select required="required" name="country_id" id="country">
                    <option value="">Select country</option>
                    <?php foreach (Countries::getCachedPairs() as $cK => $cV) : $sSelected = ($oEntity->getCountryId() == $cK) ? 'selected = "selected"' : ''; ?>
                        <option <?= $sSelected ?> value="<?= $cK ?>"><?= $cV ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>

    </fieldset>

    <div>
        <input type="submit" name="Save" value="Save"/>
    </div>

</form>