<style type="text/css">
    #phpinfo {}
    #phpinfo pre {}
    #phpinfo a:link {color: red !important;}
    #phpinfo a:first-child {display: none}
    #phpinfo a:hover {}
    #phpinfo table {}
    #phpinfo .center {}
    #phpinfo .center table {}
    #phpinfo .center th {}
    #phpinfo td, th {}
    #phpinfo h1 {}
    #phpinfo h2 {}
    #phpinfo .p {}
    #phpinfo .e {}
    #phpinfo .h {}
    #phpinfo .v {}
    #phpinfo .vr {}
    #phpinfo img {}
    #phpinfo hr {}
</style>
<div id="phpinfo">
<?php
ob_start();
phpinfo();
$pinfo = ob_get_contents();
ob_end_clean();

$pinfo = preg_replace( '%^.*<body>(.*)</body>.*$%ms','$1',$pinfo);
$pinfo = str_replace('<table', '<table class="table table-bordered table-hover"', $pinfo);
echo $pinfo;
?>
</div>
