<ul class="nav nav-pills">
    <li class="dropdown">
        <a class="dropdown-toggle"
           data-toggle="dropdown"
           href="#">
            User management
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li class="nav-header">Users</li>
            <li><a href="/admin/users/list" title="List / Search Accounts">List / Search Accounts</a></li>
            <li><a href="/admin/users/upsert" title="Add New Account">Add New Account</a></li>
            <li class="nav-header">Contacts</li>
            <li><a href="/admin/contacts/list" title="List / Search Contacts">List / Search Contacts</a></li>
            <li><a href="/admin/contacts/upsert" title="Add New Contact">Add New Contact</a></li>
            <li class="nav-header">Account Roles</li>
            <li><a href="/admin/roles/list" title="List / Search Roles">List / Search Roles</a></li>
            <li><a href="/admin/roles/upsert" title="Add New Role">Add New Role</a></li>
        </ul>
    </li>

    <li class="dropdown">
        <a class="dropdown-toggle"
           data-toggle="dropdown"
           href="#">
            Tags Management
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="/admin/tag/listother" title="Entities / Tag types">Entities / Tag Types</a></li>
            <li><a href="/admin/tag/list" title="Tags">List Tags</a></li>
            <li><a href="/admin/tag/upsert" title="Tags">Add New Tag</a></li>
        </ul>
    </li>

    <li class="dropdown">
        <a class="dropdown-toggle"
           data-toggle="dropdown"
           href="#">
            Emails
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="/admin/emails" title="Emails Dashboard">Dashboard</a></li>
            <li><a href="/admin/emails/list" title="List / Search Email Templates">List / Search Email Templates</a></li>
            <li><a href="/admin/emails/upsert" title="Add new Template">Add New Template</a></li>
            <li><a href="/admin/emails/listq" title="List / Search Queue / Archive">List / Search Queue-Archive</a></li>
        </ul>
    </li>

    <li class="dropdown">
        <a class="dropdown-toggle"
           data-toggle="dropdown"
           href="#">
            Geo
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="/admin/geo" title="Geo dashboard">Geo Dashboard</a></li>
            <li class="nav-header">Countries</li>
            <li><a href="/admin/geo/countrieslist" title="List Countries">List Countries</a></li>
            <li><a href="/admin/geo/upsertcountry" title="Add Country">Add Country</a></li>
            <li class="nav-header">Cities</li>
            <li><a href="/admin/geo/citieslist" title="List Cities">List Cities</a></li>
            <li><a href="/admin/geo/upsertcity" title="Add City">Add City</a></li>
            <li class="nav-header">States</li>
            <li><a href="/admin/geo/stateslist" title="List States">List States</a></li>
            <li><a href="/admin/geo/upsertstate" title="Add State">Add State</a></li>
        </ul>
    </li>

    <li class="dropdown">
        <a class="dropdown-toggle"
           data-toggle="dropdown"
           href="#">
            Misc
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="/admin/misc/usersettings" title="User Settings">User Settings</a></li>
            <li><a href="/admin/misc/recentsearches" title="Recent Searches">Recent Searches</a></li>
            <li class="nav-header">Other</li>
            <li><a href="/admin/misc/phpinfo" title="Php Info">Php Info</a></li>
        </ul>
    </li>
</ul>